import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Shield, Trash2, X } from 'lucide-react-native'
import { FontSize, Radius, Spacing } from '../../constants/colors'
import { useColors } from '../../contexts/ThemeContext'
import type { DocumentItem } from '../../types/document'
import type { SubjectAccessGrant, SubjectDocumentPermission, SubjectGrantType, SubjectMember, SubjectTeam } from '../../types/subject'

const titleOf = (document: DocumentItem) => document.title || document.fileName || 'Untitled document'

export default function SubjectAccessSheet({ visible, documents, grants, members, teams, grantType, targetId, permission, busy, onClose, onGrantType, onTarget, onPermission, onGrant, onUpdate, onRevoke }: {
  visible: boolean; documents: DocumentItem[]; grants: SubjectAccessGrant[]; members: SubjectMember[]; teams: SubjectTeam[]; grantType: SubjectGrantType; targetId: string; permission: SubjectDocumentPermission; busy: boolean
  onClose: () => void; onGrantType: (type: SubjectGrantType) => void; onTarget: (id: string) => void; onPermission: (permission: SubjectDocumentPermission) => void; onGrant: () => void; onUpdate: (grant: SubjectAccessGrant, permission: SubjectDocumentPermission) => void; onRevoke: (grant: SubjectAccessGrant) => void
}) {
  const C = useColors()
  const targets = grantType === 'TEAM' ? teams.map((team) => ({ id: team.id, label: team.name })) : members.filter((member) => member.status !== 'PENDING' && member.role !== 'OWNER').map((member) => ({ id: member.user.id, label: member.user.fullName || member.user.email }))
  const grouped = (type: SubjectGrantType) => grants.filter((grant) => grant.granteeType === type)
  return <Modal animationType="slide" onRequestClose={onClose} transparent visible={visible}>
    <View style={[styles.overlay, { backgroundColor: C.overlayDark }]}><View style={[styles.sheet, { backgroundColor: C.card }]}>
      <View style={styles.header}><View style={[styles.icon, { backgroundColor: C.primaryDim }]}><Shield color={C.primary} size={21} /></View><View style={styles.headerText}><Text style={[styles.title, { color: C.text }]}>{documents.length > 1 ? `Access for ${documents.length} documents` : 'Share / Manage access'}</Text><Text numberOfLines={1} style={[styles.subtitle, { color: C.textSecondary }]}>{documents.length === 1 ? titleOf(documents[0]) : 'Apply one grant to all selected documents'}</Text></View><Pressable accessibilityLabel="Close access sheet" onPress={onClose} style={styles.iconButton}><X color={C.text} /></Pressable></View>
      <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
        <Text style={[styles.label, { color: C.text }]}>Grant to</Text><View style={styles.segment}>{(['USER', 'TEAM'] as const).map((type) => <Pressable key={type} onPress={() => onGrantType(type)} style={[styles.segmentButton, { borderColor: C.cardBorder }, grantType === type && { backgroundColor: C.primary, borderColor: C.primary }]}><Text style={{ color: grantType === type ? '#fff' : C.text, fontWeight: '800' }}>{type === 'USER' ? 'Member' : 'Team'}</Text></Pressable>)}</View>
        <View style={[styles.targets, { borderColor: C.cardBorder }]}>{targets.length ? targets.map((target) => <Pressable key={target.id} onPress={() => onTarget(target.id)} style={[styles.target, targetId === target.id && { backgroundColor: C.primaryDim }]}><View style={[styles.radio, { borderColor: targetId === target.id ? C.primary : C.cardBorder }]}>{targetId === target.id ? <View style={[styles.radioDot, { backgroundColor: C.primary }]} /> : null}</View><Text style={[styles.targetText, { color: C.text }]}>{target.label}</Text></Pressable>) : <Text style={[styles.empty, { color: C.muted }]}>No eligible {grantType === 'TEAM' ? 'teams' : 'members'}.</Text>}</View>
        <Text style={[styles.label, { color: C.text }]}>Permission</Text><View style={styles.segment}>{(['VIEW', 'EDIT'] as const).map((value) => <Pressable key={value} onPress={() => onPermission(value)} style={[styles.segmentButton, { borderColor: C.cardBorder }, permission === value && { backgroundColor: C.primary, borderColor: C.primary }]}><Text style={{ color: permission === value ? '#fff' : C.text, fontWeight: '800' }}>{value === 'VIEW' ? 'Viewer' : 'Editor'}</Text></Pressable>)}</View>
        <Pressable disabled={!targetId || busy} onPress={onGrant} style={[styles.primary, { backgroundColor: C.primary, opacity: targetId && !busy ? 1 : .5 }]}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>{documents.length > 1 ? `Apply to ${documents.length} documents` : 'Grant access'}</Text>}</Pressable>
        {documents.length === 1 ? <>{(['TEAM', 'USER'] as const).map((type) => <View key={type} style={styles.group}><Text style={[styles.groupTitle, { color: C.text }]}>{type === 'TEAM' ? 'Teams' : 'Members'}</Text>{grouped(type).length ? grouped(type).map((grant) => <View key={grant.id} style={[styles.grant, { borderColor: C.cardBorder }]}><View style={styles.grantMain}><Text numberOfLines={1} style={[styles.grantName, { color: C.text }]}>{grant.granteeName}</Text><Text style={[styles.grantMeta, { color: C.textSecondary }]}>{grant.permission === 'EDIT' ? 'Editor' : 'Viewer'}</Text></View><Pressable onPress={() => onUpdate(grant, grant.permission === 'VIEW' ? 'EDIT' : 'VIEW')} style={styles.toggle}><Text style={[styles.toggleText, { color: C.primary }]}>{grant.permission === 'VIEW' ? 'Make editor' : 'Make viewer'}</Text></Pressable><Pressable accessibilityLabel={`Revoke ${grant.granteeName}`} onPress={() => onRevoke(grant)} style={styles.iconButton}><Trash2 color={C.error} size={19} /></Pressable></View>) : <Text style={[styles.empty, { color: C.muted }]}>No {type === 'TEAM' ? 'team' : 'member'} grants yet.</Text>}</View>)}</> : null}
      </ScrollView>
    </View></View>
  </Modal>
}

const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: 'flex-end' }, sheet: { borderTopLeftRadius: Radius.xl, borderTopRightRadius: Radius.xl, maxHeight: '90%', minHeight: '58%', paddingBottom: Spacing.lg }, header: { alignItems: 'center', flexDirection: 'row', gap: Spacing.sm, padding: Spacing.md }, icon: { alignItems: 'center', borderRadius: Radius.md, height: 42, justifyContent: 'center', width: 42 }, headerText: { flex: 1 }, title: { fontSize: FontSize.md, fontWeight: '800' }, subtitle: { fontSize: FontSize.sm, marginTop: 2 }, iconButton: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 }, content: { gap: Spacing.sm, paddingHorizontal: Spacing.md, paddingBottom: Spacing.xl }, label: { fontSize: FontSize.sm, fontWeight: '800', marginTop: Spacing.sm }, segment: { flexDirection: 'row', gap: Spacing.sm }, segmentButton: { alignItems: 'center', borderRadius: Radius.md, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 44 }, targets: { borderRadius: Radius.md, borderWidth: 1, maxHeight: 180, overflow: 'hidden' }, target: { alignItems: 'center', flexDirection: 'row', gap: Spacing.sm, minHeight: 46, paddingHorizontal: Spacing.md }, radio: { alignItems: 'center', borderRadius: Radius.full, borderWidth: 2, height: 18, justifyContent: 'center', width: 18 }, radioDot: { borderRadius: Radius.full, height: 8, width: 8 }, targetText: { flex: 1, fontSize: FontSize.sm }, primary: { alignItems: 'center', borderRadius: Radius.md, justifyContent: 'center', minHeight: 48, marginTop: Spacing.sm }, primaryText: { color: '#fff', fontWeight: '800' }, group: { gap: Spacing.xs, marginTop: Spacing.md }, groupTitle: { fontSize: FontSize.base, fontWeight: '800' }, grant: { alignItems: 'center', borderRadius: Radius.md, borderWidth: 1, flexDirection: 'row', minHeight: 58, paddingLeft: Spacing.md }, grantMain: { flex: 1, minWidth: 0 }, grantName: { fontSize: FontSize.sm, fontWeight: '800' }, grantMeta: { fontSize: FontSize.xs, marginTop: 2 }, toggle: { justifyContent: 'center', minHeight: 44, paddingHorizontal: Spacing.sm }, toggleText: { fontSize: FontSize.xs, fontWeight: '800' }, empty: { fontSize: FontSize.sm, padding: Spacing.md, textAlign: 'center' } })
