import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { Plus, Trash2, Users } from 'lucide-react-native'
import Card from '../ui/Card'
import { FontSize, Radius, Spacing } from '../../constants/colors'
import { useColors } from '../../contexts/ThemeContext'
import type { SubjectMember, SubjectWorkspaceRole } from '../../types/subject'

export default function SubjectMembersView({ members, canManage, email, role, busy, onEmailChange, onRoleChange, onInvite, onToggleRole, onRemove }: {
  members: SubjectMember[]; canManage: boolean; email: string; role: Exclude<SubjectWorkspaceRole, 'OWNER'>; busy: string
  onEmailChange: (value: string) => void; onRoleChange: (value: 'ADMIN' | 'MEMBER') => void; onInvite: () => void; onToggleRole: (member: SubjectMember) => void; onRemove: (member: SubjectMember) => void
}) {
  const C = useColors()
  return <View style={styles.wrap}>
    {canManage ? <Card><Text style={[styles.sectionTitle, { color: C.text }]}>Add workspace member</Text><TextInput accessibilityLabel="Member email" autoCapitalize="none" keyboardType="email-address" onChangeText={onEmailChange} placeholder="Registered or new email" placeholderTextColor={C.muted} style={[styles.input, { borderColor: C.cardBorder, color: C.text }]} value={email} /><View style={styles.row}>{(['MEMBER', 'ADMIN'] as const).map((value) => <Pressable key={value} onPress={() => onRoleChange(value)} style={[styles.choice, { borderColor: C.cardBorder }, role === value && { backgroundColor: C.primary, borderColor: C.primary }]}><Text style={{ color: role === value ? '#fff' : C.text, fontWeight: '800' }}>{value === 'MEMBER' ? 'Member' : 'Admin'}</Text></Pressable>)}<Pressable accessibilityLabel="Add member" disabled={!email.trim() || busy === 'member'} onPress={onInvite} style={[styles.add, { backgroundColor: C.primary, opacity: email.trim() ? 1 : .5 }]}>{busy === 'member' ? <ActivityIndicator color="#fff" /> : <Plus color="#fff" size={20} />}</Pressable></View></Card> : null}
    {members.map((member) => <Card key={member.id}><View style={styles.row}><View style={[styles.avatar, { backgroundColor: C.primaryDim }]}><Users color={C.primary} size={20} /></View><View style={styles.main}><Text numberOfLines={1} style={[styles.name, { color: C.text }]}>{member.user.fullName || member.user.email}</Text><Text numberOfLines={1} style={[styles.email, { color: C.textSecondary }]}>{member.user.email}</Text><View style={styles.tags}><Text style={[styles.tag, { backgroundColor: C.primaryDim, color: C.primary }]}>{member.role}</Text>{member.status === 'PENDING' ? <Text style={[styles.tag, { backgroundColor: C.warningDim, color: C.warning }]}>Pending invitation</Text> : <Text style={[styles.tag, { backgroundColor: C.successDim, color: C.success }]}>Active</Text>}</View>{member.teamNames?.length ? <Text style={[styles.teams, { color: C.muted }]}>Teams: {member.teamNames.join(', ')}</Text> : null}</View></View>{canManage && member.role !== 'OWNER' ? <View style={styles.actions}><Pressable disabled={busy === member.id || member.status === 'PENDING'} onPress={() => onToggleRole(member)} style={[styles.textButton, { borderColor: C.cardBorder }]}><Text style={[styles.textButtonLabel, { color: C.primary }]}>{member.role === 'ADMIN' ? 'Make member' : 'Make admin'}</Text></Pressable><Pressable accessibilityLabel={`Remove ${member.user.email}`} onPress={() => onRemove(member)} style={styles.iconButton}><Trash2 color={C.error} size={20} /></Pressable></View> : null}</Card>)}
    {!members.length ? <Text style={[styles.empty, { color: C.muted }]}>No members in this workspace yet.</Text> : null}
  </View>
}

const styles = StyleSheet.create({ wrap: { gap: Spacing.sm }, sectionTitle: { fontSize: FontSize.base, fontWeight: '800', marginBottom: Spacing.sm }, input: { borderRadius: Radius.md, borderWidth: 1, fontSize: FontSize.base, minHeight: 46, paddingHorizontal: Spacing.md }, row: { alignItems: 'center', flexDirection: 'row', gap: Spacing.sm }, choice: { alignItems: 'center', borderRadius: Radius.md, borderWidth: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: Spacing.md }, add: { alignItems: 'center', borderRadius: Radius.md, height: 44, justifyContent: 'center', marginLeft: 'auto', width: 48 }, avatar: { alignItems: 'center', borderRadius: Radius.full, height: 42, justifyContent: 'center', width: 42 }, main: { flex: 1, minWidth: 0 }, name: { fontSize: FontSize.base, fontWeight: '800' }, email: { fontSize: FontSize.sm, marginTop: 2 }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 7 }, tag: { borderRadius: Radius.full, fontSize: FontSize.xs, fontWeight: '800', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4 }, teams: { fontSize: FontSize.xs, marginTop: 6 }, actions: { alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end', marginTop: Spacing.sm }, textButton: { borderRadius: Radius.md, borderWidth: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: Spacing.md }, textButtonLabel: { fontSize: FontSize.sm, fontWeight: '800' }, iconButton: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 }, empty: { padding: Spacing.xl, textAlign: 'center' } })
