import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { Plus, Trash2, Users, X } from 'lucide-react-native'
import Card from '../ui/Card'
import { FontSize, Radius, Spacing } from '../../constants/colors'
import { useColors } from '../../contexts/ThemeContext'
import type { SubjectMember, SubjectTeam } from '../../types/subject'

export default function SubjectTeamsView({ teams, members, canManage, name, description, inviteEmail, inviteTeamId, busy, onNameChange, onDescriptionChange, onInviteEmailChange, onInviteTeamChange, onInvite, onCreate, onDelete, onAdd, onRemove }: {
  teams: SubjectTeam[]; members: SubjectMember[]; canManage: boolean; name: string; description: string; inviteEmail: string; inviteTeamId: string; busy: string
  onNameChange: (value: string) => void; onDescriptionChange: (value: string) => void; onInviteEmailChange: (value: string) => void; onInviteTeamChange: (value: string) => void; onInvite: () => void; onCreate: () => void; onDelete: (team: SubjectTeam) => void; onAdd: (team: SubjectTeam, userId: string) => void; onRemove: (team: SubjectTeam, userId: string) => void
}) {
  const C = useColors()
  return <View style={styles.wrap}>
    {canManage ? <Card><Text style={[styles.sectionTitle, { color: C.text }]}>Create team</Text><TextInput onChangeText={onNameChange} placeholder="Team name" placeholderTextColor={C.muted} style={[styles.input, { borderColor: C.cardBorder, color: C.text }]} value={name} /><TextInput onChangeText={onDescriptionChange} placeholder="Description (optional)" placeholderTextColor={C.muted} style={[styles.input, { borderColor: C.cardBorder, color: C.text }]} value={description} /><Pressable disabled={!name.trim() || busy === 'team'} onPress={onCreate} style={[styles.primary, { backgroundColor: C.primary, opacity: name.trim() ? 1 : .5 }]}><Plus color="#fff" size={19} /><Text style={styles.primaryText}>Create team</Text></Pressable></Card> : null}
    {canManage && teams.length ? <Card><Text style={[styles.sectionTitle, { color: C.text }]}>Add a new member to a team</Text><TextInput autoCapitalize="none" keyboardType="email-address" onChangeText={onInviteEmailChange} placeholder="Member email" placeholderTextColor={C.muted} style={[styles.input, { borderColor: C.cardBorder, color: C.text }]} value={inviteEmail} /><View style={styles.teamChoices}>{teams.map((team) => <Pressable key={team.id} onPress={() => onInviteTeamChange(team.id)} style={[styles.teamChoice, { borderColor: C.cardBorder }, inviteTeamId === team.id && { backgroundColor: C.primaryDim, borderColor: C.primary }]}><Text style={{ color: inviteTeamId === team.id ? C.primary : C.text, fontWeight: '800' }}>{team.name}</Text></Pressable>)}</View><Pressable disabled={!inviteEmail.trim() || !inviteTeamId || busy === 'team-invite'} onPress={onInvite} style={[styles.primary, { backgroundColor: C.primary, opacity: inviteEmail.trim() && inviteTeamId ? 1 : .5 }]}><Plus color="#fff" size={19} /><Text style={styles.primaryText}>Add or invite to team</Text></Pressable></Card> : null}
    {teams.map((team) => { const available = members.filter((member) => member.status !== 'PENDING' && member.user.id && !team.members.some((user) => user.id === member.user.id)); return <Card key={team.id}><View style={styles.row}><View style={[styles.teamIcon, { backgroundColor: C.primaryDim }]}><Users color={C.primary} size={20} /></View><View style={styles.main}><Text style={[styles.teamName, { color: C.text }]}>{team.name}</Text><Text style={[styles.description, { color: C.textSecondary }]}>{team.description || `${team.members.length} active member(s)`}</Text></View>{canManage ? <Pressable accessibilityLabel={`Delete ${team.name}`} onPress={() => onDelete(team)} style={styles.iconButton}><Trash2 color={C.error} size={20} /></Pressable> : null}</View><View style={[styles.divider, { backgroundColor: C.cardBorder }]} />{team.members.map((user) => <View key={user.id} style={styles.memberRow}><Text numberOfLines={1} style={[styles.memberName, { color: C.text }]}>{user.fullName || user.email}</Text>{canManage ? <Pressable accessibilityLabel={`Remove ${user.email} from ${team.name}`} onPress={() => onRemove(team, user.id)} style={styles.iconButton}><X color={C.error} size={18} /></Pressable> : null}</View>)}{team.pendingMembers?.map((user) => <View key={`pending-${user.email}`} style={styles.memberRow}><Text numberOfLines={1} style={[styles.memberName, { color: C.textSecondary }]}>{user.email}</Text><Text style={[styles.pending, { backgroundColor: C.warningDim, color: C.warning }]}>Pending</Text></View>)}{canManage && available.map((member) => <Pressable key={member.id} disabled={busy === `${team.id}:${member.user.id}`} onPress={() => onAdd(team, member.user.id)} style={styles.addMember}><Plus color={C.primary} size={18} /><Text numberOfLines={1} style={[styles.addLabel, { color: C.primary }]}>Add {member.user.fullName || member.user.email}</Text></Pressable>)}</Card>})}
    {!teams.length ? <Text style={[styles.empty, { color: C.muted }]}>No teams in this workspace yet.</Text> : null}
  </View>
}

const styles = StyleSheet.create({ wrap: { gap: Spacing.sm }, sectionTitle: { fontSize: FontSize.base, fontWeight: '800', marginBottom: Spacing.sm }, input: { borderRadius: Radius.md, borderWidth: 1, fontSize: FontSize.base, marginBottom: Spacing.sm, minHeight: 46, paddingHorizontal: Spacing.md }, primary: { alignItems: 'center', borderRadius: Radius.md, flexDirection: 'row', gap: Spacing.sm, justifyContent: 'center', minHeight: 46 }, primaryText: { color: '#fff', fontWeight: '800' }, teamChoices: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginBottom: Spacing.sm }, teamChoice: { borderRadius: Radius.md, borderWidth: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: Spacing.md }, row: { alignItems: 'center', flexDirection: 'row', gap: Spacing.sm }, teamIcon: { alignItems: 'center', borderRadius: Radius.md, height: 42, justifyContent: 'center', width: 42 }, main: { flex: 1 }, teamName: { fontSize: FontSize.base, fontWeight: '800' }, description: { fontSize: FontSize.sm, marginTop: 3 }, iconButton: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 }, divider: { height: 1, marginVertical: Spacing.sm }, memberRow: { alignItems: 'center', flexDirection: 'row', minHeight: 44, paddingLeft: Spacing.sm }, memberName: { flex: 1, fontSize: FontSize.sm }, pending: { borderRadius: Radius.full, fontSize: FontSize.xs, fontWeight: '800', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4 }, addMember: { alignItems: 'center', flexDirection: 'row', gap: Spacing.sm, minHeight: 44, paddingLeft: Spacing.sm }, addLabel: { flex: 1, fontSize: FontSize.sm, fontWeight: '800' }, empty: { padding: Spacing.xl, textAlign: 'center' } })
